# Generated by Django 5.0.6 on 2024-11-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_uni', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.faculty')),
            ],
        ),
    ]
