# Generated by Django 5.0.6 on 2024-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
